title: "William Wiley"
author: "William Wiley"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
minimal: true
mathjax: true

navigation:
  - {title: Mail, icon: envelope, url: "mailto:wwiley3528@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/wwiley3528/"}
  - {title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: william wiley/contrast

plugins:
 - jekyll-feed
